### PR TITLE
add CMakeLists.txt so it can be compiled simply under windows.

### PR DESCRIPTION
**Pull request by wisherhxl**
provide Cmake file for MSVC user.
Test both on Windows and Linux, usage:
1. cd to code dir;
2. create directory build;
3. cd to build;
4. cmake ..
5. make
enjoy.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Thanks! Can you please add usage instructions as comments within this file?

**Comment by wisherhxl** [comment]
> Thanks! Can you please add usage instructions as comments within this file?

I guess README file is a better place to explain compile and install instructions, Do you want me to add it there?

**Comment by thomasrussellmurphy** [comment]
To match the existing `makefile`, please put the instructions in your `CMakeLists.txt` as well.

**Comment by wisherhxl** [comment]
OK, usage added to CMakeLists.txt

**Pull request merged**
